### ISSUE TITLE
Image upload API?

### ISSUE THREAD

**Issue by lewiswharf** [scrumpy/tiptap#138]
Awesome approach to a WYSIWYG editor.  Is there a plan to incorporate an image upload API?

What's the current workaround people are using?

**Comment by hanspagel** [comment]
There are so many ways to do an upload integration so it's hard to define one in the core. I think the we should go is to build extensions. E.g. tiptap-s3-upload

**Comment by lewiswharf** [comment]
Thanks @ilicmarko and I already saw the issue and your response prior to posting. I'm not asking the same question. Nonetheless, I appreciate your contribution!

As a reminder, I would like to know if there's going to be an image upload API at some point…

**Comment by ilicmarko** [comment]
What do you consider an "image upload API"? Because there is an `image` API provided by Tiptap, which is enough to insert an image. Tiptap can't provide any other API more universally.

As @hanspagel said, you would need to make API for each service S3, Cloudanary, Imgur etc... Also, make it somehow for the custom endpoints. This is why you have the `image` command, you send it the URL and it will insert the image, editor shouldn't care how, where you got the URL/base64 string.

**Comment by hanspagel** [comment]
We should probably set up a documentation to answer common questions like this. I'll discuss it with @philippkuehn. Until then I think we're done here. 🤓

**Comment by slava-vishnyakov** [comment]
For people coming here from Google looking how to upload the image: [How to upload dropped images with TipTap editor to the server](https://gist.github.com/slava-vishnyakov/16076dff1a77ddaca93c4bccd4ec4521)

**Comment by fdrissi** [comment]
I have created this gist , you can find how I did it with react. I am leaving this here if anyone needs it.
