### ISSUE TITLE
[Question] Editor initialized in $options

### ISSUE THREAD

**Issue by xxRockOnxx** [scrumpy/tiptap#244]
I would like to put my editor instance in `$options` but the `isActive` is not working properly. Not sure exactly what's happening, but `isActive` never turns `true`

Is there a way to do this? In previous versions, I was initializing it that way.

**Comment by erickwilder** [comment]
Could you elaborate a little more or perhaps provide a [Code Sandbox](https://codesandbox.io/) with an example of what you're trying to do?

**Comment by xxRockOnxx** [comment]
Link: https://codesandbox.io/s/vqz1vyx570

I like having my private variables or data that are not supposed to be reactive/static in `$options`. 

There's not a common convention in Vue actually, I think others prepend their variables with `$` or `_` or declare it in `created`

Is the `Editor` supposed to be reactive that's why it is not working if it was initialized in `$options`?

**Comment by erickwilder** [comment]
Yeah. I see it now. Well, there's no problem to keep your variables in the `data()` factory of your component and I don't see a valid reason to dump it into the `$options` object. I wouldn't store anything under options if it has to be read by the template - which is the case of the `Editor` instance. You *must* use it as a data property because it has to be reactive
