### ISSUE TITLE
Table Resize should apply style width

### ISSUE THREAD

**Issue by asseti6** [scrumpy/tiptap#334]
**Describe the bug**
Tables currently apply a parameter to the HTML tag as follows: `<td data-colwidth="237">`

Table resizing should also be applying the width property to the standard style tag such that exported data can be better handled externally.

**Comment by Chrissi2812** [comment]
tiptap uses [ProseMirror/prosemirror-tables](https://github.com/ProseMirror/prosemirror-tables) and therefore the column resizing is also handled by it.

So in order to achive what you want you have to extend/overwrite the `table_cell` Schema to do what you want.
- The Schema
https://github.com/ProseMirror/prosemirror-tables/blob/master/src/schema.js#L88-L95
- Where the `data-colwidth` is applied to the dom.
https://github.com/ProseMirror/prosemirror-tables/blob/master/src/schema.js#L24-L25

**Comment by asseti6** [comment]
Thanks @Chrissi2812.  Will make the change real quick and post back here for the community should someone stumble upon the thread.

**Comment by philippkuehn** [comment]
Since this is related to ProseMirror/prosemirror-tables I can't do anything here.

**Comment by yashverma2110** [comment]
> Thanks @Chrissi2812. Will make the change real quick and post back here for the community should someone stumble upon the thread.

Hey, hope you're doing good. I have stumbled upon the same issue. Do you remember how you fixed it?
