### ISSUE TITLE
Add indent and unindent buttons

### ISSUE THREAD

**Issue by Booligoosh** [scrumpy/tiptap#360]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is it possible to add indent an unindent buttons?

**Describe alternatives you've considered**
I've tried to add this functionality as an extension but it would be great to have it built-in

**Additional context**
N/A

**Comment by markadrake** [comment]
Brian Wilson has a great write-up, though it was written a very long time ago the point remains that there is no semantic tag nor any specific standard way of "indenting a paragraph". 

[For anyone who might want to read it, you can find it here.](http://www.blooberry.com/indexdot/html/topics/indent.htm)

**So, what do you want to indent?** 

The indent (forwards and backwards) is a common feature in many apps. I often find it useful when editing list items because it allows me to branch off (indent) or branch in (outdent). We all know the `tab` key can behave strangely from one device, os, and browser to the next. I think this would be a great feature to discuss.

_I'd stray away from indenting paragraphs of text, as the implementation will mostly depend on how users of this package want to render it on their frontend. I'd instead consider adding things we can control - like a `blockquote`?_

**Comment by philippkuehn** [comment]
What do you want to indent? I think this is only useful for nested lists?

**Comment by Booligoosh** [comment]
I don't actually know what it was for in particular, but I had a user ask for indent and unindent buttons like in the Gmail editor.

**Comment by Booligoosh** [comment]
I think the best way to indent would be just to wrap whatever element it is in a <blockquote> with a `style` attribute of `margin-left: whatever`.

**Comment by philippkuehn** [comment]
for now I don't have plans to implement this.
