### ISSUE TITLE
toggle between bullet list and ordered list not working

### ISSUE THREAD

**Issue by philippkuehn** [scrumpy/tiptap#4]
Find a way to toggle bullet lists and ordered lists (and maybe todolists)
![aug -27-2018 15-27-29](https://user-images.githubusercontent.com/2500670/44662369-ec445c80-aa0d-11e8-9d30-7d208eb1dc0f.gif)

**Comment by erickwilder** [comment]
I've started to investigate how to fix this issue but I want to check if someone else is already on it.

My starting point is [the discussion](https://discuss.prosemirror.net/t/list-type-toggle/948) on Prosemirror forums. There is a comment about the implementation done on `@atlaskit/editor-core` to be a working one but their implementation is quite complex. 

Looking at the various corner cases covered by that code I would try to port it from typescript to ES6 instead of reinventing the wheel. Are the maintainers here are okay with that?

**Comment by philippkuehn** [comment]
Hey @erickwilder. I also found this discussion a few weeks ago and tried my best – but without success. 😅 Maybe something with my implementation of commands isn't working here. I'd like to see someone else tackle this!

**Comment by erickwilder** [comment]
Okay. I'll continue to have a look and I hope that I can send a PR to fix it.

**Comment by laurensiusadi** [comment]
Hello, any updates on this?

**Comment by erickwilder** [comment]
@laurensiusadi 
Sorry, I didn't have much time to work on this one but I did some research a while ago and I couldn't find a "simple" solution for it. Thanks for sharing this link; in general terms, I could follow through the code and if everyone agrees I could use it as a base implementation here.

**Comment by laurensiusadi** [comment]
@erickwilder I really need this feature
