### ISSUE TITLE
Add classes to table

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [scrumpy/tiptap#409]
comment

**Comment by afwn90cj93201nixr2e1re** [comment]
For what?

**Comment by hanspagel** [comment]
please provide more context for your issues. there is no chance anyone can help you without context.

**Comment by afwn90cj93201nixr2e1re** [comment]
How we can add custom classes to table?
I need this because some frameworks reset all default

![изображение](https://user-images.githubusercontent.com/9306996/61896317-be211280-af25-11e9-8a13-1f0020598da5.png)

https://bulma.io/documentation/elements/table/

**Comment by afwn90cj93201nixr2e1re** [comment]
Im writing it now, open.

**Comment by hanspagel** [comment]
this is not a chat tool.

if you've found a bug or want to ask for a feature request: please create an issue, use the issue template, fill out all the information.

**Comment by afwn90cj93201nixr2e1re** [comment]
Lol, why i should use template if this is request?
Im using latest version, this is REQUEST, not a bug.

**Comment by Sogl** [comment]
@afwn90cj93201nixr2e1re Did you find a way to add class to something in Tiptap?

**Comment by Alendorff** [comment]
Hi @hanspagel
It looks like I'm looking for the same feature. Don't you know how to add a custom class for the existing component? In that example, when table attached in the editor, it should appear as `table.my-class` in DOM. How to achieve it? As I understand, I have to extend default Table, but I'm not sure how to do it because I'm not so familiar with prosemirror API yet.

**Comment by mike-seekwell** [comment]
@Sogl  @maksnester Did you figure out how to do this?

**Comment by RokasDie** [comment]
Yeah I also need this...

**Comment by RokasDie** [comment]
Yeah I also need this, @hanspagel maybe you could help us?
