### ISSUE TITLE
Change enter to break line instead of new paragraph

### ISSUE THREAD

**Issue by agentq15** [scrumpy/tiptap#426]
I have searched for a way to change the default behavior for Enter to be the same as Shift + Enter.
To get <br> instead of new <p>
Is it possible to change to this behavior somehow?

**Comment by MarvinMiles** [comment]
@agentq15 You're welcome :)

```
import { Editor, EditorContent, EditorMenuBar, Extension } from 'tiptap'
import { HardBreak } from 'tiptap-extensions'

...

editor = new Editor({
 extensions: [
   new HardBreak(),
   new class extends Extension {
     keys() {
       return {
         Enter(state, dispatch, view) {
           const { schema, doc, tr } = view.state

           const hard_break = schema.nodes.hard_break
           const transaction = tr.replaceSelectionWith(hard_break.create()).scrollIntoView()
           view.dispatch(transaction)
           return true
         }
       }
     }
   }(),
 ],
 content: '',

...
```

**Comment by dafen** [comment]
@MarvinMiles Thank you so much! Works like a charm!

**Comment by agentq15** [comment]
@MarvinMiles Thank you! Works great!

**Comment by xyNNN** [comment]
This is not working for me. Still a press on "enter" creates a new paragraph? 

Any ideas? Thanks!

`
    this.editor = new Editor({
      content: this.modelValue,
      extensions: [
        StarterKit,
        HardBreak,
        new class extends Extension {
          keys() {
            return {
              Enter(state, dispatch, view) {
                const {schema, doc, tr} = view.state;

                const hard_break = schema.nodes.hard_break;
                const transaction = tr.replaceSelectionWith(hard_break.create()).scrollIntoView();
                view.dispatch(transaction);

                return true;
              }
            }
          }
        }(),
      ]
    });
`

**Comment by xyNNN** [comment]
Thank you very much!

**Comment by greeto** [comment]
Hi all thanks!
But it's not working well with:
1. Tiptap v2
2. When using UL, OL, Headings and staff like that...
Someone managed to solved it?

**Comment by gldkru** [comment]
Actual

**Comment by Robxxcraft** [comment]
Help. I am use tiptap v2 in vue js 3.
I can't preserve hardbreak using paragraph in enter using StarterKit extension. It doesn't seem to close the paragraph on enter

**Comment by Robxxcraft** [comment]
Please Do hardbreak when paragraph or heading is empty

**Comment by rosnaib11** [comment]
> Rather than creating an entirely new extension, you can just configure the HardBreak extension to also use the Enter key.
> 
> ```
>     this.editor = new Editor({
>       content: this.modelValue,
>       extensions: [
>         StarterKit,
>         HardBreak.extend({
>           addKeyboardShortcuts () {
>             return {
>               Enter: () => this.editor.commands.setHardBreak()
>             }
>           }
>         })
>       ]
>     });
> ```
> 
> It's worth noting that this will cause issues with lists and other formatting extensions since it will insert `<br>` inline instead of wrapping the new line in an element.

This will work but if you use this with bullet list or ordered list your whole text will include to the list

**Comment by d-ohorodnykov** [comment]
still actual

**Comment by rajbirjohar** [comment]
Hey guys, just thought I would throw my solution in so it works well with headings and such. Instead of inserting a hardbreak, I created another paragraph and instead set a minimum height to the `<p>` tag using CSS equal to a fixed line height. This way, empty `<p>` tags still respect a height.

```tsx
 const CustomHardBreak = Hardbreak.extend({
    addKeyboardShortcuts () {
      return {
        Enter: () => this.editor.chain().createParagraphNear().run()
      }
    }
  });


.journal p {
    margin: 1em 0;
    font-size: 20px;
    line-height: 30px;
    min-height: 30px;
}
```

**Comment by Henribou** [comment]
@greeto @domnantas and @rosnaib11 I managed to deal with bullet list and ordered list with the following

```
HardBreak.extend({
    addKeyboardShortcuts() {
        return {
            Enter: () => {
                if (this.editor.isActive('orderedList') || this.editor.isActive('bulletList')) {
                    return this.editor.chain().createParagraphNear().run();
                }
                return this.editor.commands.setHardBreak();
            },
        };
    },
}),
```

**Comment by yndotdev** [comment]
> Rather than creating an entirely new extension, you can just configure the HardBreak extension to also use the Enter key.
> 
> ```
>     this.editor = new Editor({
>       content: this.modelValue,
>       extensions: [
>         StarterKit,
>         HardBreak.extend({
>           addKeyboardShortcuts () {
>             return {
>               Enter: () => this.editor.commands.setHardBreak()
>             }
>           }
>         })
>       ]
>     });
> ```
> 
> It's worth noting that this will cause issues with lists and other formatting extensions since it will insert `<br>` inline instead of wrapping the new line in an element.

May God bless you and your (future) children.

**Comment by ArnNied** [comment]
To anyone reading this, you might not need this at all.

I was encountering the same problem and asked myself this issue's question but by setting my "Enter" key to set a HardBreak, it causes issues with multiple extensions such as headings and list.

It turns out that the `<p>` tag does get rendered on the output (not talking about the editor) but it has a height of 0 so it acts like there is no new line at all. All you have to do is set a height (or a min-height) for the `<p>` in your css.

OR, configure the Paragraph extension to add a class/style for the height.

```javascript
const CustomStarterKit = StarterKit.configure({
  // ...
  paragraph: {
    HTMLAttributes: {
      class: 'min-h-[1rem]'
    }
  }
});
```
Or this.
```javascript
const CustomParagraph = Paragraph.configure({
  HTMLAttributes: {
    class: 'min-h-[1rem]'
  }
});
```

Then include it in your list of extensions. I was using Tailwind there, but you get the idea.

Although, feel free to use this issue's solution if it IS exactly what you're looking for.

**Comment by ArnNied** [comment]
I was encountering the same problem and asked myself this question but by setting my "Enter" key to set a HardBreak, it causes issues with multiple extensions such as headings and list.

It turns out that after a brief inspection of the element inside the editor and my output, it renders a`<p>` tag and inside it contain's a `<br />` which acts as a line break. BUT, that `<br />` tag does not get included on the output so the `<p>` tag does not have any height at all.

Two other methods that works:

1. With CSS, you can do something like this (probably more reliable than the second method):
[https://stackoverflow.com/questions/66457359/how-to-keep-a-paragraph-height-even-when-there-is-no-text-in-it](https://stackoverflow.com/questions/66457359/how-to-keep-a-paragraph-height-even-when-there-is-no-text-in-it)
```css
.ProseMirror p:empty::before {
  content: '';
  display: inline-block;
}
```
I attached the ProseMirror css class to my output as well, change it acording to your need. This inserts an empty element so that the `<p>` height will be kept.


2. Configure the Paragraph extension to add a class/style for the "height" (this can be a simple height, min-height, margin, etc).

```javascript
const CustomStarterKit = StarterKit.configure({
  // ...
  paragraph: {
    HTMLAttributes: {
      class: 'min-h-[1rem]'
    }
  }
});
```
Or this.
```javascript
const CustomParagraph = Paragraph.configure({
  HTMLAttributes: {
    class: 'min-h-[1rem]'
  }
});
```

Then include it in your list of extensions. I was using Tailwind there, but you get the idea.

**Comment by techreagan** [comment]
```javascript
this.editor = new Editor({
	editorProps: {
		attributes: {
			class: "text",
		},
	},
	content: '<p>Hello world</p>',
	extensions: [
		StarterKit.configure({
			document: false,
		}),
		Document,
		Paragraph,
		Text,
		Highlight,
	],
	onUpdate: ({ editor }) => {
		this.content = editor.getHTML().replace(/<p><\/p>/g, "<br>");
	},
});
```

```javascript
editor.getHTML().replace(/<p><\/p>/g, "<br>");
```
this solved mine for me. Just replace the empty paragraph (`<p/></p>`) with `<br>`

**Comment by heatherdg** [comment]
> ```js
> this.editor = new Editor({
> 	editorProps: {
> 		attributes: {
> 			class: "text",
> 		},
> 	},
> 	content: '<p>Hello world</p>',
> 	extensions: [
> 		StarterKit.configure({
> 			document: false,
> 		}),
> 		Document,
> 		Paragraph,
> 		Text,
> 		Highlight,
> 	],
> 	onUpdate: ({ editor }) => {
> 		this.content = editor.getHTML().replace(/<p><\/p>/g, "<br>");
> 	},
> });
> ```
> 
> ```js
> editor.getHTML().replace(/<p><\/p>/g, "<br>");
> ```
> 
> this solved mine for me. Just replace the empty paragraph (`<p/></p>`) with `<br>`

Not great - doesn't work with bullet points

**Comment by LeoDoldan7** [comment]
If you need the line breaks _outside_ of the editor (for example, in the backend to send as an email) you can use `node-html-parser`:

```
const replaceEmptyParagraphs = (content: string) => {
  const decodedContent = decode(content);
  const root = parse(decodedContent);

  for (const element of root.childNodes) {
    if (element.rawTagName === 'p' && element.textContent === '') {
      element.textContent = '<br/>';
    }
  }

  const html = root.toString();
  return html;
};
```

**Comment by matan1905** [comment]
I added this to my CSS
```css
.tiptap > p {
    margin-top: 0 !important;
}
```
