### ISSUE TITLE
Pasting from Microsoft Word not working

### ISSUE THREAD

**Issue by RandomAshes** [scrumpy/tiptap#60]
I'm not sure if this is a bug, or if I'm missing something but I would love some help if anyone else has any ideas what might resolve it.

I'm trying to use the tiptap rich text editor with my vue app. **I need to be able to copy and paste from a word document into the editor**. 

For some reason, when I try to copy and paste from my word document into my instance of the tiptap editor, it won't paste anything with the normal paste command. However, if I paste the same thing into one of the examples on https://tiptap.scrumpy.io/, it pastes just fine. I can get it to paste in my instance if I use the "Paste and match style" option on my Mac, but I can't for the life of me figure out why the normal paste command won't work properly for me.

I wasn't sure if there was something strange with my app environment, so I created a brand new vue cli instance and pasted the code straight from https://github.com/heyscrumpy/tiptap/blob/master/examples/Components/Routes/Basic/index.vue into it. I installed tiptap & tiptap-extensions. It still wouldn't let me copy and paste from a word document with the normal paste command.

I pulled down the tiptap repo and ran that, and it works properly there, so I'm wondering if there's some dependency or setting I'm not aware that I need to have setup?

Any suggestions as to what might be causing the problem would be greatly appreciated.

**Comment by joeweiss** [comment]
I'm seeing the same thing @RandomAshes, also using clean vue cli instance. It works in other places.

**Comment by philippkuehn** [comment]
@joeweiss or @RandomAshes: can you provide a test repo?

**Comment by philippkuehn** [comment]
Closed due to inactivity

**Comment by aizotov** [comment]
I'm having the same issue. Pasting content from Tiptap into other Tiptap editors and Google Docs works fine - formatting such as bold and underline is preserved. However, pasting from Tiptap into MS Wordpad OR MS Wordpad into Tiptap loses formatting (pastes as plaintext).

**Comment by smrifat1411** [comment]
@aizotov @NitichaiSawangsai — the "falls back to plain text" symptom usually means the paste handler never recognized the clipboard HTML as HTML in the first place. Desktop Word's clipboard payload is wrapped in `<html xmlns:o="urn:schemas-microsoft-com:office:office" ...>` with a huge inline `<style>` block of `mso-*` rules ahead of the actual content — some paste pipelines bail out or strip too aggressively when they hit that, and what's left reads as unstructured text.

If Tiptap's newer [Paste Handler extension](https://tiptap.dev/docs/editor/extensions/functionality/paste-handler) doesn't fully clear it for you, I ran into the same clipboard shape building an exam tool and pulled the fix into a small library — [wordpaste](https://github.com/smrifat1411/wordpaste) (MIT, zero deps, ~3.5 kB). Disclosure: I wrote it. Same drop-in as my note on #1526:

```js
import { transformPastedHTML } from 'wordpaste';

new Editor({
  extensions: [StarterKit],
  editorProps: { transformPastedHTML },
});
```

It parses the `mso-*` markers before stripping them rather than after, which is usually where formatting gets lost. You can drop your own Word doc into the [playground](https://smrifat1411.github.io/wordpaste/) (runs locally) to see what's actually on the clipboard before deciding if this is your bug.
